### PR TITLE
Update students.txt

### PR DESCRIPTION
**Pull request by s6xizhou**
student ID added

### CODE REVIEW

**Comment by s6xizhou** [comment]
Thanks a lot! I still have a problem, I searched for the google group from
the slide, but only get a result as not exist. Can you help me join the
group?

Best
Xiaotian

**Comment by diegoesteves** [comment]
hello,

you should search just "nlp_labs_unibonn_wise1718" in google's group
webpage.

https://groups.google.com/


Best regards,

D. Esteves
SDA Research Group
University of Bonn, Germany
-- “Inspiration exists, but it has to find you working.” Pablo Picasso --

**Comment by s6xizhou** [comment]
Hello,

I am afraid still can not find any result by searching
"nlp_labs_unibonn_wise1718"
in this webpage. 😞 I attach the screenshot of my Browser.

**Comment by diegoesteves** [comment]
OK, please send me your google email privately and I will add you

Best regards,

D. Esteves
SDA Research Group
University of Bonn, Germany
-- “Inspiration exists, but it has to find you working.” Pablo Picasso --

**Pull request merged**
